# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class EditUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 201)
        self.dateTimeEdit= QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(), Form)
        self.dateTimeEdit.setDisplayFormat('yy/MM/dd hh:mm')
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 30, 261, 41))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit.setStyleSheet("font: 13pt \"Calibri\";")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(300, 31, 81, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(20, 90, 361, 41))
        self.textEdit.setObjectName("textEdit")
        self.ConfirmEditButton = QtWidgets.QPushButton(Form)
        self.ConfirmEditButton.setGeometry(QtCore.QRect(140, 150, 131, 41))
        self.ConfirmEditButton.setObjectName("ConfirmEditButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Low"))
        self.comboBox.setItemText(1, _translate("Form", "Avg"))
        self.comboBox.setItemText(2, _translate("Form", "High"))
        self.ConfirmEditButton.setText(_translate("Form", "Confirm"))
