# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1067, 670)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(570, 70, 241, 41))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(850, 70, 91, 41))
        self.pushButton.setStyleSheet("font: 10pt \"Calibri\" \"bold\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 135, 91, 41))
        self.pushButton_2.setStyleSheet("font: 10pt \"Calibri\" \"bold\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(570, 140, 161, 31))
        self.dateTimeEdit.setStyleSheet("font: 10pt \"Calibri\";")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(740, 140, 71, 31))
        self.comboBox.setStyleSheet("font: 10pt \"Calibri\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(30, 210, 501, 381))
        self.tableView.setStyleSheet("font: 10pt \"Calibri\";")
        self.tableView.setObjectName("tableView")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(550, 210, 491, 381))
        self.calendarWidget.setStyleSheet("font: 13pt \"Calibri\" \"bold\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 30, 271, 81))
        self.label.setStyleSheet("font: 48pt \"Calibri\" \"bold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 140, 361, 51))
        self.label_2.setStyleSheet("font: italic 16pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
#===============================================================================================

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_2.setText(_translate("Form", "Remove"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "None"))
        self.label.setText(_translate("Form", "mAIdo"))
        self.label_2.setText(_translate("Form", "Manage Your Life with the Power of AI!!"))
