# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1067, 670)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(570, 70, 241, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("font: 13pt \"Calibri\";")
        self.AddButton = QtWidgets.QPushButton(Form)
        self.AddButton.setGeometry(QtCore.QRect(850, 70, 91, 41))
        self.AddButton.setObjectName("AddButton")
        self.AddButton.setStyleSheet("font:13pt \"Calibri\";")
        self.AddButton.clicked.connect(Form.add)
        self.DeleteButton = QtWidgets.QPushButton(Form)
        self.DeleteButton.setGeometry(QtCore.QRect(850, 135, 91, 41))
        self.DeleteButton.setObjectName("DeleteButton")
        self.DeleteButton.setStyleSheet("font:13pt \"Calibri\";")
        self.DeleteButton.clicked.connect(Form.Delete)
        self.TaskDue = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(), Form)
        self.TaskDue.setGeometry(QtCore.QRect(570, 140, 161, 31))
        self.TaskDue.setDisplayFormat('yy/MM/dd hh:mm')
        self.TaskDue.setObjectName("dateTimeEdit")
        self.TaskDue.setStyleSheet("font: 13pt \"Calibri\";")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(740, 140, 71, 31))
        self.comboBox.setStyleSheet("font: 13pt \"Calibri\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 210, 501, 381))
        self.tableWidget.setStyleSheet("font: 13pt \"Calibri\";")
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(550, 210, 491, 381))
        self.calendarWidget.setStyleSheet("font:bold 13pt \"Calibri\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 30, 271, 81))
        self.label.setStyleSheet("font:bold 36pt \"Calibri\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 140, 361, 51))
        self.label_2.setStyleSheet("font:bold italic 16pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
#=============================================================================================================
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.calendarWidget.setVerticalHeaderFormat(0)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.LongDayNames)

        #self.calendarWidget.setNavigationBarVisible(0)
        self.calendarWidget.setSelectionMode(0)
        # self.calendarWidget.ShowToday()


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "mAIDo-demo"))
        self.AddButton.setText(_translate("Form", "Add"))
        self.DeleteButton.setText(_translate("Form", "Remove"))
        self.comboBox.setItemText(1, _translate("Form", "1"))
        self.comboBox.setItemText(2, _translate("Form", "2"))
        self.comboBox.setItemText(0, _translate("Form", "NaN"))
        self.label.setText(_translate("Form", "mAIDo"))
        self.label_2.setText(_translate("Form", "Manage Your Life with AI!"))


