# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(807, 466)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(430, 30, 220, 35))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("font: 10pt \"Calibri\";")
        self.AddButton = QtWidgets.QPushButton(Form)
        self.AddButton.setGeometry(QtCore.QRect(680, 30, 75, 30))
        self.AddButton.setObjectName("AddButton")
        self.AddButton.setStyleSheet("font:10pt \"Calibri\";")
        self.AddButton.clicked.connect(Form.add)
        self.DeleteButton = QtWidgets.QPushButton(Form)
        self.DeleteButton.setGeometry(QtCore.QRect(680, 80, 75, 30))
        self.DeleteButton.setObjectName("DeleteButton")
        self.DeleteButton.setStyleSheet("font:10pt \"Calibri\";")
        self.DeleteButton.clicked.connect(Form.Delete)
        self.TaskDue = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(), Form)
        self.TaskDue.setGeometry(QtCore.QRect(430, 80, 130, 30))
        self.TaskDue.setDisplayFormat('yy/MM/dd hh:mm')
        self.TaskDue.setObjectName("dateTimeEdit")
        self.TaskDue.setStyleSheet("font: 8pt \"Calibri\";")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(580, 80, 70, 30))
        self.comboBox.setStyleSheet("font: 8pt \"Calibri\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 140, 365, 230))
        self.tableWidget.setStyleSheet("font: 10pt \"Calibri\";")
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setVerticalHeaderFormat(0)
        self.calendarWidget.setHorizontalHeaderFormat(0)
        self.calendarWidget.setNavigationBarVisible(0)
        self.calendarWidget.setSelectionMode(0)
        # self.calendarWidget.ShowToday()
        self.calendarWidget.setGeometry(QtCore.QRect(430, 140, 320, 230))
        self.calendarWidget.setStyleSheet("font:bold 8pt \"Calibri\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 220, 60))
        self.label.setStyleSheet("font:bold 36pt \"Calibri\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 350, 35))
        self.label_2.setStyleSheet("font:bold italic 16pt \"Calibri\";")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "mAIDo-demo"))
        self.AddButton.setText(_translate("Form", "Add"))
        self.DeleteButton.setText(_translate("Form", "Remove"))
        self.comboBox.setItemText(1, _translate("Form", "1"))
        self.comboBox.setItemText(2, _translate("Form", "2"))
        self.comboBox.setItemText(0, _translate("Form", "NaN"))
        self.label.setText(_translate("Form", "mAIDo"))
        self.label_2.setText(_translate("Form", "Manage Your Life with AI!"))


