# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *


class Login_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 297)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(115, 30, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setStyleSheet("font:bold 34pt \"Calibri\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 91, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 81, 41))
        self.label_3.setObjectName("label_3")
        self.UserNameTextEdit = QtWidgets.QLineEdit(Form)
        self.UserNameTextEdit.setGeometry(QtCore.QRect(110, 110, 201, 41))
        self.UserNameTextEdit.setObjectName("UserNameTextEdit")
        self.passWordTextEdit = QtWidgets.QLineEdit(Form)
        self.passWordTextEdit.setGeometry(QtCore.QRect(110, 170, 201, 41))
        self.passWordTextEdit.setObjectName("passWordTextEdit")
        self.LoginButton = QtWidgets.QPushButton(Form)
        self.LoginButton.setGeometry(QtCore.QRect(70, 230, 111, 41))
        self.LoginButton.setObjectName("LoginButton")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(200, 230, 135, 41))
        self.checkBox.setObjectName("checkBox")
        self.LoginButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.retranslateUi(Form)
        self.UserNameTextEdit.setAttribute(Qt.WA_InputMethodEnabled, False)
        QtCore.QMetaObject.connectSlotsByName(Form)
        ##
        self.passWordTextEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        #Form.setTabOrder(self.UserNameTextEdit.focusProxy(), self.passWordTextEdit.focusProxy())
        #Form.setTabOrder(self.passWordTextEdit.focusProxy() ,self.UserNameTextEdit.focusProxy())

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "mAIdo     "))
        self.label_2.setText(_translate("Form", "UserName"))
        self.label_3.setText(_translate("Form", "Password"))
        self.LoginButton.setText(_translate("Form", "Log in"))
        self.checkBox.setText(_translate("Form", "Remember Pass"))
