# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lion_\Desktop\mAIDo\layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(807, 466)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(430, 30, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(680, 30, 75, 31))
        self.pushButton.setStyleSheet("font: 10pt \"Calibri\" \"bold\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(680, 70, 75, 31))
        self.pushButton_2.setStyleSheet("font: 10pt \"Calibri\" \"bold\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(430, 80, 131, 22))
        self.dateTimeEdit.setStyleSheet("font: 10pt \"Calibri\";")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(580, 80, 69, 22))
        self.comboBox.setStyleSheet("font: 10pt \"Calibri\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(50, 140, 341, 231))
        self.tableView.setStyleSheet("font: 10pt \"Calibri\";")
        self.tableView.setObjectName("tableView")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(430, 140, 321, 231))
        self.calendarWidget.setStyleSheet("font: 10pt \"Calibri\" \"bold\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 221, 61))
        self.label.setStyleSheet("font: 48pt \"Calibri\" \"bold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 341, 31))
        self.label_2.setStyleSheet("font: italic 16pt \"Calibri\";")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_2.setText(_translate("Form", "Remove"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "NaN"))
        self.label.setText(_translate("Form", "mAIdo"))
        self.label_2.setText(_translate("Form", "Manage Your Life with the Power of AI!!"))
